#!/usr/bin/env python3
"""
Generate lightweight *.generated.h files for KraftonEngine reflected headers.

The current ObjectMacros.h expects GENERATED_BODY() to expand through:

    CURRENT_FILE_ID##_GENERATED_BODY

This script scans headers under Source/, finds reflected declarations that use
GENERATED_BODY(), and writes a matching generated header next to each source
header.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


REFLECTED_DECL_RE = re.compile(
    r"\bU(?P<kind>CLASS|STRUCT)\s*\([^)]*\)\s*"
    r"(?P<decl>class|struct)\s+"
    r"(?:(?:[A-Z_][A-Z0-9_]*|final|abstract)\s+)*"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)


@dataclass(frozen=True)
class ReflectedHeader:
    header: Path
    generated_header: Path
    file_id: str
    class_names: tuple[str, ...]


def strip_comments(text: str) -> str:
    """Remove C/C++ comments while preserving line structure for simple scans."""
    text = re.sub(r"/\*.*?\*/", lambda m: "\n" * m.group(0).count("\n"), text, flags=re.DOTALL)
    text = re.sub(r"//.*", "", text)
    return text


def make_file_id(root: Path, header: Path) -> str:
    rel = header.relative_to(root).as_posix()
    file_id = re.sub(r"[^A-Za-z0-9_]", "_", rel)
    if not file_id or file_id[0].isdigit():
        file_id = f"KR_{file_id}"
    return file_id


def find_reflected_headers(root: Path, source_dir: Path) -> tuple[list[ReflectedHeader], list[str]]:
    reflected: list[ReflectedHeader] = []
    warnings: list[str] = []

    for header in sorted(source_dir.rglob("*.h")):
        if header.name.endswith(".generated.h"):
            continue

        text = header.read_text(encoding="utf-8-sig")
        scan_text = strip_comments(text)
        declarations = [m.group("name") for m in REFLECTED_DECL_RE.finditer(scan_text)]

        if not declarations:
            continue

        if not re.search(r"\bGENERATED_BODY\s*\(", scan_text):
            warnings.append(f"{header.relative_to(root)}: reflected declaration without GENERATED_BODY()")
            continue

        reflected.append(
            ReflectedHeader(
                header=header,
                generated_header=header.with_name(f"{header.stem}.generated.h"),
                file_id=make_file_id(root, header),
                class_names=tuple(declarations),
            )
        )

    return reflected, warnings


def render_generated_header(item: ReflectedHeader, root: Path) -> str:
    source_rel = item.header.relative_to(root).as_posix()
    class_list = ", ".join(item.class_names)

    return (
        "// This file is generated by Tools/GenerateHeaders.py. Do not edit manually.\n"
        f"// Source: {source_rel}\n"
        f"// Reflected types: {class_list}\n"
        "#pragma once\n"
        "\n"
        "#undef CURRENT_FILE_ID\n"
        f"#define CURRENT_FILE_ID {item.file_id}\n"
        "\n"
        f"#define {item.file_id}_GENERATED_BODY \\\n"
        "    static void RegisterProperties(UClass* Class);\n"
    )


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if old == content:
            return False

    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate KraftonEngine *.generated.h headers.")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Project root. Defaults to the parent directory of Tools/.",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=None,
        help="Header scan directory. Defaults to <root>/Source.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be generated without writing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    source_dir = (args.source_dir or root / "Source").resolve()

    if not source_dir.exists():
        print(f"error: source directory does not exist: {source_dir}")
        return 1

    reflected, warnings = find_reflected_headers(root, source_dir)

    changed = 0
    for item in reflected:
        content = render_generated_header(item, root)
        rel_generated = item.generated_header.relative_to(root)
        if args.dry_run:
            print(f"would generate {rel_generated} for {', '.join(item.class_names)}")
            continue

        if write_if_changed(item.generated_header, content):
            changed += 1
            print(f"generated {rel_generated}")
        else:
            print(f"unchanged {rel_generated}")

    for warning in warnings:
        print(f"warning: {warning}")

    action = "would process" if args.dry_run else "processed"
    print(f"{action} {len(reflected)} reflected header(s), {changed} changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
