// This file is generated by Tools/GenerateHeaders.py. Do not edit manually.
// Source: Source/Engine/Object/Object.h
// Reflected types: UObject
#pragma once

#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Source_Engine_Object_Object_h

#define Source_Engine_Object_Object_h_GENERATED_BODY \
    static void RegisterProperties(UClass* Class);
