// This file is generated by Tools/GenerateHeaders.py. Do not edit manually.
// Source: Source/Engine/Component/Movement/MovementComponent.h
// Reflected types: UMovementComponent
#pragma once

#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Source_Engine_Component_Movement_MovementComponent_h

#define Source_Engine_Component_Movement_MovementComponent_h_GENERATED_BODY \
    static void RegisterProperties(UClass* Class);
