// This file is generated by Tools/GenerateHeaders.py. Do not edit manually.
// Source: Source/Engine/GameFramework/AActor.h
// Reflected types: AActor
#pragma once

#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Source_Engine_GameFramework_AActor_h

#define Source_Engine_GameFramework_AActor_h_GENERATED_BODY \
    static void RegisterProperties(UClass* Class);
