// This file is generated by Tools/GenerateHeaders.py. Do not edit manually.
// Source: Source/Engine/Component/ActorComponent.h
// Reflected types: UActorComponent
#pragma once

#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Source_Engine_Component_ActorComponent_h

#define Source_Engine_Component_ActorComponent_h_GENERATED_BODY \
    static void RegisterProperties(UClass* Class);
