// This file is generated by Tools/GenerateHeaders.py. Do not edit manually.
// Source: Source/Engine/Component/CameraComponent.h
// Reflected types: UCameraComponent
#pragma once

#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Source_Engine_Component_CameraComponent_h

#define Source_Engine_Component_CameraComponent_h_GENERATED_BODY \
    static void RegisterProperties(UClass* Class);
