// This file is generated by Tools/GenerateHeaders.py. Do not edit manually.
// Source: Source/Engine/Component/SceneComponent.h
// Reflected types: USceneComponent
#pragma once

#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Source_Engine_Component_SceneComponent_h

#define Source_Engine_Component_SceneComponent_h_GENERATED_BODY \
    static void RegisterProperties(UClass* Class);
